/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fachrul Hasan (https://sketchfab.com/fachrulhasan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kawaii-cute-flying-robot-e8e85bce90644fa486ac21e033c71d92
Title: Kawaii & Cute Flying Robot
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import {useMediaQuery} from 'react-responsive';

const CuteRobot = (props) => {
  const isMobile = useMediaQuery({maxWidth: 768});
  const isTablet = useMediaQuery({minWidth: 768, maxWidth: 1024});
  const { nodes, materials } = useGLTF('/robot/scene.gltf')
  return (
    <Float floatIntensity={1}>
      <group {...props} rotation={[-Math.PI / 2, 0, 0]} scale={isMobile ? 1.5 : isTablet ? 2.5 : 3}>
        <lineSegments geometry={nodes.Object_2.geometry} material={materials['Material.002']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials['Material.003']}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/robot/scene.gltf')
export default CuteRobot